version: '3.1'
services:

  redis:
    image: 'redis:6-alpine'
    container_name: deployment-redis
    ports:
      - "127.0.0.1:6382:6379"

  mongodb:
    image: mongo
    container_name: deployment-mongodb
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=pass
    command: --quiet